version: '3.8'

services:
  kerberos:
    build: .
    ports:
      - "88:88"
      - "749:749"
    hostname: kerberos
    domainname: auth-protocols.com
    networks:
      - auth-protocols-network

networks:
  auth-protocols-network:
    external: true
